version: '3.8'

services:
  zion-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zion_reminder_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=zionreminderdb;Username=postgres;Password=postgres
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-placeholder-password}
      # Use the line below if you don't want to use the .env file
      # - EMAIL_PASSWORD=your-actual-email-password
      - OPENAI__APIKEY=${OPENAI__APIKEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - zion-network

  postgres:
    image: postgres:16-alpine
    container_name: zion_reminder_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zionreminderdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - zion-network

  # Optionally add pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: zion_reminder_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - zion-network

volumes:
  postgres_data:

networks:
  zion-network:
    driver: bridge
