// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zion.Reminder.Data;

#nullable disable

namespace Zion.Reminder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250516091958_RenamingModels")]
    partial class RenamingModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zion.Reminder.Models.ReminderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Reminders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 16, 9, 19, 58, 309, DateTimeKind.Utc).AddTicks(1604),
                            Description = "Finish the API documentation for the reminder service",
                            DueDate = new DateTime(2025, 5, 23, 9, 19, 58, 309, DateTimeKind.Utc).AddTicks(2043),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Complete project documentation"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 16, 9, 19, 58, 309, DateTimeKind.Utc).AddTicks(2352),
                            Description = "Discuss project progress and roadblocks",
                            DueDate = new DateTime(2025, 5, 19, 9, 19, 58, 309, DateTimeKind.Utc).AddTicks(2353),
                            IsCompleted = false,
                            Priority = 1,
                            Title = "Weekly team meeting"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
